num1 = int(input("Primeiro número "))
num2 = int(input("Segundo número "))

print("Adição {} + {}: {}".format(num1, num2, num1 + num2))
print("Subtração {} - {}: {}".format(num1, num2, num1 - num2))
print("Multiplicação {} * {}: {}".format(num1, num2, num1 * num2))
print("Potência {} ** {}: {}".format(num1, num2, num1 ** num2))
print("Divisão {} / {}: {}".format(num1, num2, num1 / num2))
print("Divisão inteira {} // {}: {}".format(num1, num2, num1 // num2))
print("Resto da divisão {} % {}: {}".format(num1, num2, num1 % num2))